### ISSUE TITLE
Use GitHub as a CDN?

### ISSUE THREAD

**Issue by shazdeh** [atlemo/SubtlePatterns#20]
Hi,
is it possible from both legal and technical point to link to these patterns on GitHub?
Any insight is appreciated.

**Comment by Bugster** [comment]
GitHub is slower than using an actual CDN or even your own hosting most 
of the time.

**Comment by tom2strobl** [comment]
It is generally not a good idea, because the file is being served as text/plain and as such being blocked in Internet Explorer on Windows 7 for instance (because of the wrong MIME type).

**Comment by 1j01** [comment]
You can use rawgit (https://cdn.rawgit.com/subtlepatterns/SubtlePatterns/gh-pages/irongrip.png), which serves proper Content-Types. But keep in mind that data URIs would be preferable in most cases, because they don't even require a separate request, and some of these patterns are so small that they only take up like 200 characters in base 64. Unless you need to support ie7 (http://caniuse.com/datauri)

**Comment by DanielRuf** [comment]
GitHub explicitely says that it should not be used as CDN.

**Comment by praisedpk** [comment]
Github is not a CDN. You can use dedicated [subtlepatterns CDN](https://pagecdn.com/lib/subtlepatterns) for direct linking of pattern images from your website.
